### ISSUE TITLE
Overflow in Mobile View

### ISSUE THREAD

**Issue by TartejBrothers** [Hassam-kh/Profile#1]
- There is some overflow-x in the mobile view of the website. 
![image](https://github.com/Hassam-kh/Profile/assets/112921727/0f20959d-2c55-4ad8-8783-41ad16af3e69)

```css
body{
     overflow-x: hidden
}
```
Try this
